name: Build
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed
    strategy:
      matrix:
       target: [ i686-w64-mingw32.shared, x86_64-w64-mingw32.shared ]
       build_type: [ Release, Debug ]
    steps:
      - name: Update packages
        run: zypper -n --gpg-auto-import-keys ref
      - name: Upgrade packages
        run: zypper -n --gpg-auto-import-keys dup -l -y
      - name: Install openSUSE dependencies
        run: zypper -n --gpg-auto-import-keys install glibc glibc-extra glibc-locale glibc-i18ndata glibc-32bit gcc gcc-c++ shadow which patch gperf wget curl git diffutils make cmake libtool pkg-config autoconf automake makeinfo meson ninja intltool tar gzip bzip2 xz p7zip p7zip-full lzip zip unzip gtk-doc gettext-tools scons bison flex ruby orc linux-glibc-devel glibc-devel libstdc++-devel file-devel libopenssl-devel libffi-devel gdk-pixbuf-devel python3-base python3-Mako python3-packaging python3-PyYAML libzstd-devel libzstd-devel-static pcre2-devel zlib-devel fmt-devel xxhash-devel doctest-devel Mesa-libGL-devel Mesa-libEGL-devel Mesa-libGLESv2-devel
      - name: Link python 3
        run: ln -s /usr/bin/python3 /usr/bin/python
      - uses: actions/checkout@v5
      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Build
        shell: bash
        run: make -j 4 MXE_TARGETS="${{matrix.target}}" MXE_BUILD_TYPE="${{matrix.build_type}}" MXE_VERBOSE=1
